name: Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# defaults:
#   run:
#     shell: bash

# permissions:
#   contents: read

jobs:
  flow-test:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    name: Flow
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}

    # services:
    #   mongo:
    #     image: 'mongo:3.7'
    #     ports:
    #       # Maps port 27017 on service container to the host
    #       - 27017:27017

    steps:
      - name: Run Flow test
        run: npm run flow check --all
